### PR TITLE
implemented holympics-controller

### PR DESCRIPTION
**Pull request by bharath-ka**

### CODE REVIEW

**Comment by d3fkon** [comment]
Implement a validator for all routes expecting data from the `request` object using `express-validation`
Routes to be changed includes `/addpoints` and `/subpoints`

**Comment by d3fkon** [comment]
@bharath-ka  Add one more route to retrieve a list of all college names. A simple unauthenticated GET request would suffice

**Comment by d3fkon** [comment]
@bharath-ka  Also, considering authenticating the `/subapoints` and `/addpoints` route so not anyone can randomly increase or decrease the points to a particular college. But let this not be a priority at this point. I'll add this as an issue so we can track it and make sure it's done before the final release

**Comment by d3fkon** [comment]
@bharath-ka could you separate the validator schema for `holympics` and put into it's own `holympicsValidator.js` file under the `validators` directory as a part of separation of concerns?

**Comment by bharath-ka** [comment]
Okay

**Pull request merged**
